---
kind: pipeline
type: docker
name: build

steps:
  - name: test
    image: rust:slim
    commands:
      - cargo build --verbose --all
      - cargo test --verbose --all

trigger:
  branch:
    - master
    - ci/*
