---
kind: pipeline
type: docker
name: build

steps:
  - name: test
    image: rust:latest
    commands:
      - cargo build --verbose --all
      - cargo test --verbose --all
    depends_on:
      - clone

  - name: clippy
    image: rust:latest
    commands:
      - rustup component add clippy
      - cargo clippy --all-targets --all-features
    depends_on:
      - clone

  - name: fmt
    image: rust:latest
    commands:
      - rustup component add rustfmt
      - cargo fmt --check
    depends_on:
      - clone 

trigger:
  branch:
    - master
    - ci/*
