[package]
name = "cdecao"
version = "0.1.0"
authors = ["Michael Thies <mail@mhthies.de>"]
edition = "2018"

[dependencies]
ndarray = "^0.12"
log = "^0.4"
env_logger = "^0.6"
num-traits = "^0.2"
ordered-float = "^1.0"